CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.SUPPLIER
AS
SELECT * FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."SUPPLIER" LIMIT 100;

CREATE TABLE DEMO_DB.PUBLIC.SUPPLIER_CLONE
CLONE DEMO_DB.PUBLIC.SUPPLIER;

 -- SELECT * FROM DEMO_DB.PUBLIC.SUPPLIER_CLONE;

-- Update the clone table and copy the query id
UPDATE SUPPLIER_CLONE SET S_PHONE = '###'; --01c3f50d-0001-aeee-000d-d87a00160162

CREATE OR REPLACE TABLE DEMO_DB.PUBLIC.time_travel_supplier_clone
CLONE DEMO_DB.PUBLIC.SUPPLIER_CLONE before (statement => '01c3f50d-0001-aeee-000d-d87a00160162');

SELECT * FROM DEMO_DB.PUBLIC.time_travel_supplier_clone;

-- If we delete the source table, does the clone still exist?
DROP TABLE DEMO_DB.PUBLIC.SUPPLIER;

SELECT * FROM DEMO_DB.PUBLIC.SUPPLIER_CLONE;