CREATE DATABASE TIMETRAVEL_EXERCISE;
CREATE SCHEMA TIMETRAVEL_EXERCISE.COMPANY_X;

CREATE TABLE CUSTOMER AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER
LIMIT 500;

SELECT * FROM CUSTOMER;

--Drop the schema (assuming it happened by accident)

DROP SCHEMA TIMETRAVEL_EXERCISE.COMPANY_X;

UNDROP SCHEMA TIMETRAVEL_EXERCISE.COMPANY_X;